version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel-backpack-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-backpack

  # Nginx Service
  web:
    image: nginx:1.25
    container_name: laravel-backpack-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-backpack
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: laravel-backpack-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_backpack
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: backpack
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - laravel-backpack-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-backpack

  # Valkey Service (Redis fork)
  valkey:
    image: valkey/valkey:latest
    container_name: laravel-backpack-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - laravel-backpack-valkey:/data
    networks:
      - laravel-backpack

networks:
  laravel-backpack:
    driver: bridge

volumes:
  laravel-backpack-mysql:
    driver: local
  laravel-backpack-valkey:
    driver: local