version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: statamic-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - statamic

  # Nginx Service
  web:
    image: nginx:1.25
    container_name: statamic-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - statamic
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: statamic-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: statamic
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: statamic
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - statamic-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - statamic

  # Valkey Service (Redis fork)
  valkey:
    image: valkey/valkey:latest
    container_name: statamic-valkey
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - statamic-valkey:/data
    networks:
      - statamic

networks:
  statamic:
    driver: bridge

volumes:
  statamic-mysql:
    driver: local
  statamic-valkey:
    driver: local